### ISSUE TITLE
ADC: Documentation: Description EOC bit  in ADC_SR is wrong

### ISSUE THREAD

**Issue by KamilDuljas** [STMicroelectronics/STM32CubeF7#113]
In reference manual RM0410:

ADC control register 2 (ADC_CR2) describes EOCS as following:

![image](https://github.com/STMicroelectronics/STM32CubeF7/assets/87798948/5933c94e-a75f-45d4-815b-ddd59f2d0731)

But in ADC status register (ADC_SR) EOCS is described as following:
![image](https://github.com/STMicroelectronics/STM32CubeF7/assets/87798948/cb3f9c22-ea7a-4481-aa21-10a8791b9560)

Conversion complete should be described as EOCS=1, not EOCS=0

**Comment by RJMSTM** [comment]
ST Internal Reference: 170657

**Comment by RJMSTM** [comment]
Hello @KamilDuljas,

Your request is being processed internally for update. So, the correction will be available in the next publication of the reference manual RM0410. And since there are no patches in our software, please allow me to close this issue.

Thank you very much for your attention. We look forward to hearing from you.

With regards,
