### ISSUE TITLE
Add HAL_TIM_GetFrequency

### ISSUE THREAD

**Issue by jrahlf** [STMicroelectronics/STM32CubeF7#32]
Hi,

it would be great if there as a function to get the frequency of a given timer, e.g. HAL_TIM_GetFrequency()
Currently one has to query APB1 or APB2, but before one has to know which peripheral bus the timer is connected to, which you generally do not know.

This has been requested on the forums before, e.g. [1](https://community.st.com/s/question/0D50X00009nL3TbSAK/function-to-return-value-of-apb1-apb2-timer-clocks), [2](https://community.st.com/s/question/0D50X00009XkfZg/how-do-i-get-the-frequency-of-a-timer-in-stm32f769i)

This affects all STM32Fxx packages.

**Comment by ASELSTM** [comment]
Hi @jrahlf,

Thank you for this report.

Actually such a request is out of HAL driver scoop since it requires system information that are unknown at driver level such as the APBx clock the timer is clocked by or the APBx clock prescaler configuration. So, such service must be handled on top of the HAL driver.  Therefore, our development team regrets to decline your request. Thank you for your understanding.

Please allow me then to close this thread. Thank you for your comprehension and thank you again for your contribution.

With regards,
