### ISSUE TITLE
stm32 lwip sample projects have problem at cable unplug mcu start

### ISSUE THREAD

**Issue by mohammadpoorkhalili** [STMicroelectronics/STM32CubeF7#49]
hi . when i using every sample from lwip with every st official evaluation board and series stm32f4 and stm32f7 , when mcu start without cable connected , after plug cable device connot connect to network.
This problem still persists when I create a project with Cubemx program

**Comment by mohammadpoorkhalili** [comment]
hi this problem when freertos is not enabled, can be solve by editing MX_LWIP_Init function.
but when i enabled freertos can't find way for solve this problem.

**Comment by ASELSTM** [comment]
Hi @mohammadpoorkhalili,

This is actually a normal behavior. Indeed, after timeout connection, the device gets static address.
You might then change the application behavior to use only dynamic address or to use only static address or to switch differently from dynamic to static.

As this issue is not valid, please allow me then to close this thread.

With regards,
