### ISSUE TITLE
Nucleo F746ZG not working when generating code with all peripherals initialized

### ISSUE THREAD

**Issue by xRadx** [STMicroelectronics/STM32CubeF7#64]
**Describe the set-up**
 * Nucleo F746ZG
 * STM32CubeIDE 1.8.0

**Describe the bug**
The board does not work after uploading generated code.

**How To Reproduce**
Create  a project from the board selector (nucleo F746ZG) with all peripherals initialized and generate code straight away (no setting changes).
Put
    HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_0);
    /* Insert delay 100 ms */
    HAL_Delay(100);
in loop.

No led blinking.

After uploading example, the board is back alive.

**Comment by RKOUSTM** [comment]
Hi @xRadx,

Thank you for your report. This point is related to the CubeMX generation problem and not directly related to the firmware published in this repository. 

We tried to reproduce the issue you have described using [this](https://github.com/STMicroelectronics/STM32CubeF7/tree/master/Projects/STM32F746ZG-Nucleo/Examples/GPIO/GPIO_IOToggle) example on [STM32F746ZG-Nucleo](https://github.com/STMicroelectronics/STM32CubeF7/tree/master/Projects/STM32F746ZG-Nucleo) board published in this repository, with no success. You can refer to the GPIO_IOToggle example to develop your application. This example shows how how to configure and use GPIOs through the HAL API. 

Now, as this issue is not directly related to some software component published within this repository (CMSIS, HAL, BSP, etc.) but rather to our ecosystem (namely the Cube MX tool), please allow me to close it.

Thank you again for your report. We are looking forward to reading from you again.

With regards,
