### ISSUE TITLE
Incorrect code generation for PLL of F767

### ISSUE THREAD

**Issue by AndreiCherniaev** [STMicroelectronics/STM32CubeF7#67]
Please see https://community.st.com/s/question/0D53W00000euVZLSA2/incorrect-code-generation-for-pll-of-f767

https://github.com/STMicroelectronics/STM32CubeF7/blob/f8cefdf02e8ad7fd06bd38a2dd85a55ecdbe92a9/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.c#L601

**Comment by ASELSTM** [comment]
Hi @AndreiCherniaev,

The point you reported is actually related to the **CubeMX** generation problem and not to the firmware published in this repository. Unfortunately, we don't treat aspect related to CubeMX tool in our GitHub repositories.  They are rather treated at the [STM32CubeMX](https://community.st.com/s/topic/0TO0X000000BTr8WAG/stm32cubemx) dedicated page of the **ST Community** . 

Since this issue is not directly related to the STM32Cube firmware but rather to our ecosystem, please allow me then to close this thread. Thank you for your comprehension. 

With regards,
